# Generated by Django 6.1.1 on 2026-09-17 16:15

import django_mongodb_backend.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Device",
            fields=[
                (
                    "id",
                    django_mongodb_backend.fields.ObjectIdAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("equipos", models.CharField(max_length=100)),
                ("marca", models.CharField(max_length=100)),
                ("modelo", models.CharField(max_length=100)),
            ],
        ),
    ]
